//AuthLoading
export const SAVEUSER = 'SAVEUSER';
export const SAVEUSERSETTINGS = 'SAVEUSERSETTINGS';
// Login
export const ONLOGINCHANGE = 'ONLOGINCHANGE';
export const ONLOGINLOADING = 'ONLOGINLOADING';
export const LOGINSUCCESS = 'LOGINSUCCESS';
export const LOGINFAILED = 'LOGINFAILED';
// Register
export const ONREGISTERCHANGE = 'ONREGISTERCHANGE';
export const ONREGISTERLOADING = 'ONREGISTERLOADING';
export const REGISTERSUCCESS = 'REGISTERSUCCESS';
export const REGISTERFAILED = 'REGISTERFAILED';
//Home
export const GETPOSTSSUCCESS = 'GETPOSTSSUCCESS';
export const GETPOSTSFAILED = 'GETPOSTSFAILED';
export const ONLIKE = 'ONLIKE';
export const ONCOMMENTCHANGE = 'ONCOMMENTCHANGE';
export const ONCOMMENT = 'ONCOMMENT';
export const ONCOMMENTLOADING = 'ONCOMMENTLOADING';
export const ONREPLYCOMMENTLOADING = 'ONREPLYCOMMENTLOADING';
export const ADDEDCOMMENTTOFILTER = 'ADDEDCOMMENTTOFILTER';
export const GETUSERLIKED = 'GETUSERLIKED';
export const LIKESMODALLOADING = 'LIKESMODALLOADING';
export const GETREPLYCOMMENT = 'GETREPLYCOMMENT';
export const DELETECOMMENT = 'DELETECOMMENT';
export const ONDELETELOADING = 'ONDELETELOADING';
export const DELETEREPLY = 'DELETEREPLY';
export const ONDELETEREPLYLOADING = 'ONDELETEREPLYLOADING';
export const HIDEPOST = 'HIDEPOST';
export const ONREFRESHING = 'ONREFRESHING';
export const ONPOSTLOADING = 'ONPOSTLOADING';
export const ONDELETEPOST = 'ONDELETEPOST';
export const ONDELETEPOSTLOADING = 'ONDELETEPOSTLOADING';
export const ONEDITPOST = 'ONEDITPOST';
export const ONEDITLOADING = 'ONEDITLOADING';
export const ONDISABLEDLOADING = 'ONDISABLEDLOADING';
export const POSTFAILED = 'POSTFAILED';
export const ONREPLYPENDING = 'ONREPLYPENDING';
//JOBS
export const GETJOBSSSUCCESS = 'GETJOBSSSUCCESS';
export const GETJOBSFAILED = 'GETJOBSFAILED';
export const SAVEJOB = 'SAVEJOB';
export const ONJOBCOMMENT = 'ONJOBCOMMENT';
export const ADDEDJOBCOMMENTTOFILTER = 'ADDEDJOBCOMMENTTOFILTER';
export const ONJOBCOMMENTLOADING = 'ONJOBCOMMENTLOADING';
export const PRIVATEMESSAGESUCCESS = 'PRIVATEMESSAGESUCCESS';
export const PRIVATEMESSAGEFAILED = 'PRIVATEMESSAGEFAILED';
export const ONPRIVATEMESSAGELOADING = 'ONPRIVATEMESSAGELOADING';
export const ADDJOBLOADING = 'ADDJOBLOADING';
export const ONDELETEJOBLOADING = 'ONDELETEJOBLOADING';
export const ONDELETEJOB = 'ONDELETEJOB';
export const ONEDITJOB = 'ONEDITJOB';
export const ONJOBLOADING = 'ONJOBLOADING';
export const ONJOBDISABLEDLOADING = 'ONJOBDISABLEDLOADING';
export const ONDELETEJOBIMAGEPHOTO = 'ONDELETEJOBIMAGEPHOTO';
export const ONDELTEJOBIMAGEPHOTOLOADING = 'ONDELTEJOBIMAGEPHOTOLOADING';
export const ONDELETECOMMENTLOADING = 'ONDELETECOMMENTLOADING';
export const ONDELETECOMMENT = 'ONDELETECOMMENT';
export const ONJOBSREFRESHING = 'ONJOBSREFRESHING';
export const GETJOBREPLYCOMMENT = 'GETJOBREPLYCOMMENT';
export const ONJOBREPLYCOMMENTLOADING = 'ONJOBREPLYCOMMENTLOADING';
export const ONDELETEJOBREPLYLOADING = 'ONDELETEJOBREPLYLOADING';
export const ONDELETEREPLY = 'ONDELETEREPLY';
export const ONJOBREPLYPENDING = 'ONJOBREPLYPENDING';
export const ONCHANGELOCATION = 'ONCHANGELOCATION';
export const ONSELECTLOCATION = 'ONSELECTLOCATION';
//Profile
export const GETUSERDETAILS = 'GETUSERDETAILS';
export const GETUSERSETTINGS = 'GETUSERSETTINGS';
export const ONCHANGESETTINGS = 'ONCHANGESETTINGS';
export const ONCHANGEJOBNOTIFRANGE = 'ONCHANGEJOBNOTIFRANGE';
export const SAVESETTINGSSUCCESSFULL = 'SAVESETTINGSSUCCESSFULL';
export const USERSETTINGSLOADING = 'USERSETTINGSLOADING';
export const SAVESETTINGSLOADING = 'SAVESETTINGSLOADING';
//Messaging
export const GETUSERS = 'GETUSERS';
export const ONMESSAGINGREFRESHING = 'ONMESSAGINGREFRESHING';
export const GETMESSAGES = 'GETMESSAGES';
export const ONGETMESSAGESLOADING = 'ONGETMESSAGESLOADING';
export const SENDMESSAGE = 'SENDMESSAGE';
export const ONSENDMESSAGELOADING = 'ONSENDMESSAGELOADING';
export const ONSEARCH = 'ONSEARCH';
//UsersProfile
export const GETUSERSDETAILS = 'GETUSERSDETAILS';
export const GETUSERSSTATS = 'GETUSERSSTATS';
export const GETUSERSPOSTS = 'GETUSERSPOSTS';
export const GETUSERSLOADING = 'GETUSERSLOADING';
